language: elixir
elixir:
  - 1.2.6
otp_release:
  - 19.0
services:
  - postgresql
before_script:
  - psql -c 'create database esioci;' -U postgres
script:
  - "MIX_ENV=test mix do deps.get && mix compile && mix ecto.migrate && mix coveralls"
